USE foodbank;

-- DO NOT FORMAT

-- debug
DROP TABLE IF EXISTS shift_registration;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS remembered_logins;

DROP TABLE IF EXISTS opening_hours;

DROP TABLE IF EXISTS shifts;

-- db creation 
CREATE TABLE
    users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        email VARCHAR(255) NOT NULL UNIQUE,
        phone VARCHAR(11) NOT NULL,
        password VARCHAR(255) NOT NULL,
        role ENUM ("staff", "volunteer") NOT NULL,
        is_over_18 BOOLEAN NOT NULL
    );

CREATE TABLE
    remembered_logins (
        id INT AUTO_INCREMENT,
        uid VARCHAR(255) NOT NULL,
        date DATETIME NOT NULL,
        PRIMARY KEY (id, uid)
    );

CREATE TABLE
    opening_hours (
        id INT AUTO_INCREMENT PRIMARY KEY,
        date DATE NOT NULL UNIQUE,
        open_time TIME NOT NULL,
        close_time TIME NOT NULL
    );

CREATE TABLE
    shifts (
        id INT AUTO_INCREMENT PRIMARY KEY,
        shift_date DATE NOT NULL,
        start_time TIME,
        end_time TIME,
        category ENUM("yellow", "blue", "orange", "purple") NOT NULL
    );

CREATE TABLE
    shift_registration (
        id INT AUTO_INCREMENT PRIMARY KEY,
        shift_id INT NOT NULL,
        user_id INT NOT NULL,
        UNIQUE (shift_id, user_id),
        FOREIGN KEY (shift_id) REFERENCES shifts (id),
        FOREIGN KEY (user_id) REFERENCES users (id)
    );

-- insert staff account
INSERT INTO
    users (name, email, phone, password, role, is_over_18)
VALUES
    (
        "Test",
        "test@email.com",
        "12345678901",
        "$2y$12$g8HbZkrCtslS8c.GLPjTsuvKTVEw2Pjx5kabaZnC65qpFGnODNlX2",
        "staff",
        1
    );

-- password = password123
-- insert opening hours (this entire week, next entire week, and one day extra for bounds checking)
INSERT INTO
    opening_hours (date, open_time, close_time)
VALUES
    (
        DATE_SUB(
            DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY),
            INTERVAL 1 DAY
        ),
        '12:12:12',
        '12:12:12'
    ),
    (
        DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY),
        '10:00:00',
        '19:00:00'
    ),
    (
        DATE_ADD(
            DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY),
            INTERVAL 1 DAY
        ),
        '10:00:00',
        '19:00:00'
    ),
    (
        DATE_ADD(
            DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY),
            INTERVAL 2 DAY
        ),
        '11:00:00',
        '15:00:00'
    ),
    (
        DATE_ADD(
            DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY),
            INTERVAL 3 DAY
        ),
        '10:00:00',
        '18:00:00'
    ),
    (
        DATE_ADD(
            DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY),
            INTERVAL 4 DAY
        ),
        '10:00:00',
        '19:30:00'
    ),
    (
        DATE_ADD(
            DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY),
            INTERVAL 5 DAY
        ),
        '09:00:00',
        '19:30:00'
    ),
    (
        DATE_ADD(
            DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY),
            INTERVAL 6 DAY
        ),
        '10:30:00',
        '16:00:00'
    ),
    (
        DATE_ADD(
            DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY),
            INTERVAL 7 DAY
        ),
        '10:00:00',
        '19:00:00'
    ),
    (
        DATE_ADD(
            DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY),
            INTERVAL 8 DAY
        ),
        '10:00:00',
        '19:00:00'
    ),
    (
        DATE_ADD(
            DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY),
            INTERVAL 9 DAY
        ),
        '11:00:00',
        '15:00:00'
    ),
    (
        DATE_ADD(
            DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY),
            INTERVAL 10 DAY
        ),
        '10:00:00',
        '18:00:00'
    ),
    (
        DATE_ADD(
            DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY),
            INTERVAL 11 DAY
        ),
        '10:00:00',
        '19:30:00'
    ),
    (
        DATE_ADD(
            DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY),
            INTERVAL 12 DAY
        ),
        '09:00:00',
        '19:30:00'
    ),
    (
        DATE_ADD(
            DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY),
            INTERVAL 13 DAY
        ),
        '10:30:00',
        '16:00:00'
    ),
    (
        DATE_ADD(
            DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY),
            INTERVAL 14 DAY
        ),
        '12:12:12',
        '12:12:12'
    );

-- insert shift hours
INSERT INTO shifts (shift_date, start_time, end_time, category) VALUES 
(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), "09:00:00","12:00:00","yellow"),
(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), "11:30:00","15:00:00","blue"),
(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), "14:00:00","18:00:00","orange"),
(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), "17:00:00","20:00:00","purple"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 1 DAY), "09:00:00","12:00:00","yellow"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 1 DAY), "11:30:00","15:00:00","blue"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 1 DAY), "14:00:00","18:00:00","orange"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 1 DAY), "17:00:00","20:00:00","purple"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 2 DAY), "10:00:00","13:00:00","yellow"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 2 DAY), "12:00:00","15:00:00","blue"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 2 DAY), "14:00:00","16:30:00","orange"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 2 DAY), NULL,NULL,"purple"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 3 DAY), "09:00:00","12:00:00","yellow"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 3 DAY), "11:30:00","14:30:00","blue"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 3 DAY), "14:00:00","17:00:00","orange"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 3 DAY), "16:30:00","19:00:00","purple"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 4 DAY), "09:00:00","12:00:00","yellow"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 4 DAY), "11:30:00","15:00:00","blue"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 4 DAY), "14:00:00","18:00:00","orange"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 4 DAY), "17:00:00","20:00:00","purple"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 5 DAY), "08:00:00","11:30:00","yellow"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 5 DAY), "10:30:00","15:00:00","blue"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 5 DAY), "14:00:00","18:00:00","orange"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 5 DAY), "17:00:00","20:00:00","purple"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 6 DAY), "10:00:00","13:00:00","yellow"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 6 DAY), "12:00:00","15:00:00","blue"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 6 DAY), "14:00:00","16:30:00","orange"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 6 DAY), NULL,NULL,"purple"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 7 DAY), "09:00:00","12:00:00","yellow"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 7 DAY), "11:30:00","15:00:00","blue"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 7 DAY), "14:00:00","18:00:00","orange"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 7 DAY), "17:00:00","20:00:00","purple"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 8 DAY), "09:00:00","12:00:00","yellow"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 8 DAY), "11:30:00","15:00:00","blue"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 8 DAY), "14:00:00","18:00:00","orange"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 8 DAY), "17:00:00","20:00:00","purple"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 9 DAY), "10:00:00","13:00:00","yellow"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 9 DAY), "12:00:00","15:00:00","blue"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 9 DAY), "14:00:00","16:30:00","orange"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 9 DAY), NULL,NULL,"purple"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 10 DAY), "09:00:00","12:00:00","yellow"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 10 DAY), "11:30:00","14:30:00","blue"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 10 DAY), "14:00:00","17:00:00","orange"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 10 DAY), "16:30:00","19:00:00","purple"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 11 DAY), "09:00:00","12:00:00","yellow"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 11 DAY), "11:30:00","15:00:00","blue"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 11 DAY), "14:00:00","18:00:00","orange"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 11 DAY), "17:00:00","20:00:00","purple"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 12 DAY), "08:00:00","11:30:00","yellow"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 12 DAY), "10:30:00","15:00:00","blue"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 12 DAY), "14:00:00","18:00:00","orange"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 12 DAY), "17:00:00","20:00:00","purple"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 13 DAY), "10:00:00","13:00:00","yellow"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 13 DAY), "12:00:00","15:00:00","blue"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 13 DAY), "14:00:00","16:30:00","orange"),
(DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY (CURDATE()) DAY), INTERVAL 13 DAY), NULL,NULL,"purple");